spring.application.name=Smartlab-backend



spring.datasource.url=jdbc:mysql://localhost:3306/smartlab_db
spring.datasource.username=root
spring.datasource.password=dhanu@94

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8081

#spring.application.name=Smartlab-backend
#
#spring.datasource.url=jdbc:mysql://switchback.proxy.rlwy.net:29672/railway
#spring.datasource.username=root
#spring.datasource.password=ZeRDecwwFfPYWMtmguxDsvBvhPJVXqLC
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#server.port=8080
